# Generated by Django 4.1.5 on 2023-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Karta płatnicza'), ('cash', 'Gotówka')], default='card', max_length=24, verbose_name='Sposób płatności'),
        ),
    ]
